services:
  asterisk:
    image: ghcr.io/jarodbruce/asterisk-homelab:latest
    healthcheck:
      disable: true
    networks:
      - hostnet
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == node01]

networks:
  hostnet:
    name: host
    external: true