[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
PHONEALL=PJSIP/201&PJSIP/202

[internal]
exten => _[01].,1,NoOp(Call from ${CALLERID(all)} to ${EXTEN})
              same => n,Answer()
              same => n,Wait(1)
              same => n,Dial(PJSIP/${EXTEN}@ht813)

exten => _2XZ,1,Dial(PJSIP/${EXTEN},,tT)

;[pstnincomming]
exten => 200,1,NoOp(Call from PSTN to 200)
              same => n,Answer()
              same => n,Wait(2)
              same => n,Dial(${PHONEALL},150,tT)

exten => fax,1,NoOp(Receiving Fax)
              same => n,Set(FILENAME=${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)})-${UNIQUEID}
              same => n,ReceiveFax(/srv/FAX/FAXIN/${FILENAME}.tiff,d)
              same => n,NoOp(FaxStatus: ${FAXOPT(status)})
              same => n,NoOp(FaxError: ${FAXOPT(error)})
              same => n,NoOp(FaxPages: ${FAXOPT(pages)})
              same => n,Hangup()