[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]
PHONEALL=PJSIP/6001&PJSIP/6002&PJSIP/6003

[internal]
; ===== 外線発信 (0または1から始まる番号はHT813へ送る) =====
exten => _[01].,1,NoOp(Call from ${CALLERID(all)} to ${EXTEN})
        same => n,Dial(PJSIP/${EXTEN}@ht813,60,tT)
        same => n,Hangup()

; ===== 市外局番(0294)省略時の発信設定
exten => _ZXXXXX,1,NoOp(Local call: adding area code 0294)
        same => n,Dial(PJSIP/0294${EXTEN}@ht813,60,trT)
        same => n,Hangup()

; ===== 内線同士の通話 =====
exten => _2XX,1,NoOp(Internal Call from ${CALLERID(all)} to ${EXTEN})
        same => n,Dial(PJSIP/${EXTEN},60,tT)
        same => n,Hangup()

exten => _6XXX,1,NoOp(Internal Call from ${CALLERID(all)} to ${EXTEN})
        same => n,Dial(PJSIP/${EXTEN},60,tT)
        same => n,Hangup()

; ===== 外線からの着信 (200) =====
exten => 200,1,NoOp(Call from PSTN to 200)
        same => n,TrySystem(/var/lib/asterisk/scripts/on_call.sh "${CALLERID(num)}" &)
        same => n,Dial(${PHONEALL},60,trT)
        same => n,Hangup()

; FAX (共通処理)
exten => fax,1,NoOp(FAX detected! Receiving FAX...)
        same => n,System(curl -d "fax" ntfy.sh/KxgaRAdAYycAOnTS)
        same => n,Set(FILENAME=${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)})-${UNIQUEID}
        same => n,ReceiveFax(/srv/FAX/FAXIN/${FILENAME}.tiff,d)
        same => n,TrySystem(/var/lib/asterisk/scripts/printfax.sh ${FILENAME})
        same => n,Hangup()