[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0
local_net=192.168.0.0/16  ; 追加: ローカルIPの範囲

;;; HT813 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[ht813]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=ht813
aors=ht813
language = ja
direct_media = no
fax_detect = yes
rewrite_contact = yes  ; 追加: 連絡先IPを送信元のもので上書きする
force_rport = yes      ; 追加: ポートのズレを自動補正する

[ht813]
type=auth
auth_type=userpass
password=ht813
username=ht813

[ht813]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes
contact=sip:192.168.1.201:5062

[ht813-identify]
type=identify
endpoint=ht813
match=192.168.1.201
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;; 201 ;;;;;;;;;;
[201]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=201
aors=201
language = ja
direct_media = no
;fax_detect = yes

[201]
type=auth
auth_type=userpass
password=********
username=201

[201]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes

;;;;;;;;;; 202 ;;;;;;;;;;
[202]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=202
aors=202
language = ja
direct_media = no
;fax_detect = yes

[202]
type=auth
auth_type=userpass
password=********
username=202

[202]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes

; -------------------------------------------------------------
; --- 内線電話機 6001 の設定 ---
; -------------------------------------------------------------
[6001]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=6001
aors=6001
language = ja
direct_media=no

[6001]
type=auth
auth_type=userpass
password=6001
username=6001

[6001]
type=aor
max_contacts=10

; -------------------------------------------------------------
; --- 内線電話機 6002 の設定 ---
; -------------------------------------------------------------
[6002]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=6002
aors=6002
language = ja
direct_media=no

[6002]
type=auth
auth_type=userpass
password=6002
username=6002

[6002]
type=aor
max_contacts=10

; -------------------------------------------------------------
; --- 内線電話機 6003 の設定 ---
; -------------------------------------------------------------
[6003]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=6003
aors=6003
language = ja
direct_media=no

[6003]
type=auth
auth_type=userpass
password=6003
username=6003

[6003]
type=aor
max_contacts=10