[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

;;; HT813 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[ht813]
type=endpoint
;context=pstnincomming
context=internal
disallow=all
allow=ulaw
auth=ht813-auth
aors=ht813-aor
language = ja
direct_media = no
fax_detect = yes

[ht813-auth]
type=auth
auth_type=userpass
password=ht813
username=ht813

[ht813-aor]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes
contact=sip:192.168.1.8:5062

[ht813-identify]
type=identify
endpoint=ht813
match=192.168.1.8
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;; 201 ;;;;;;;;;;
[201]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=201-auth
aors=201-aor
language = ja
direct_media = no
;fax_detect = yes

[201-auth]
type=auth
auth_type=userpass
password=********
username=201

[201-aor]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes

;;;;;;;;;; 202 ;;;;;;;;;;
[202]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=202-auth
aors=202-aor
language = ja
direct_media = no
;fax_detect = yes

[202-auth]
type=auth
auth_type=userpass
password=********
username=202

[202-aor]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes

;;;;;;;;;; 203 ;;;;;;;;;;
[203]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=203-auth
aors=203-aor
language = ja
direct_media = no
;fax_detect = yes

[203-auth]
type=auth
auth_type=userpass
password=********
username=203

[203-aor]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes