[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

;;; HT813 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[7973422]
type=endpoint
;context=pstnincomming
context=internal
disallow=all
allow=ulaw
auth=7973422
aors=7973422
language = ja
direct_media = no
fax_detect = yes

[7973422]
type=auth
auth_type=userpass
password=********
username=7973422

[7973422]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes
contact=sip:192.168.1.8:5062

[ht813-identify]
type=identify
endpoint=7973422
match=192.168.1.8

[ht813-faxout-identify]
type=identify
endpoint=faxout-7973422
match=192.168.1.8

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;; 201 ;;;;;;;;;;
[201]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=201
aors=201
language = ja
direct_media = no
;fax_detect = yes

[201]
type=auth
auth_type=userpass
password=********
username=201

[201]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes

;;;;;;;;;; 202 ;;;;;;;;;;
[202]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=202
aors=202
language = ja
direct_media = no
;fax_detect = yes

[202]
type=auth
auth_type=userpass
password=********
username=202

[202]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes

;;;;;;;;;; 203 ;;;;;;;;;;
[203]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=203
aors=203
language = ja
direct_media = no
;fax_detect = yes

[203]
type=auth
auth_type=userpass
password=********
username=203

[203]
type=aor
max_contacts=1
qualify_frequency=60
remove_existing=yes